### PR TITLE
Update graduates index file with Yamada Marina showroom

### PR DESCRIPTION
**Pull request by skeith**

### CODE REVIEW

**Comment by wlerin** [comment]
Don't delete Marina's old room. It doesn't make much difference, and there's still potentially a need for it (at least on my end, can't think why anyone else would need it).

I could just add it manually then close this, but it would be nice to actually have you on the contributors list finally :P

**Comment by skeith** [comment]
How do I name her on graduates.jdex?

Won't it conflict if her name is the same?

**Comment by wlerin** [comment]
Not unless she streams from her old room at the same time as her new room. The only thing that has to be unique is the room id. Also please call that "room_id" not the old "showroom_id" (I can actually fix that myself before merging, it's just the deletion that's hard to undo).

**Comment by skeith** [comment]
got it, will fix

**Pull request merged**
