### PR TITLE
Update optional-requirements.txt

### PR DESCRIPTION
**Pull request by skeith**

### CODE REVIEW

**Comment by wlerin** [comment]
I don't even remember why I don't install this by default.

**Comment by skeith** [comment]
should I move it to `requirements.txt` instead? or you have other plan

**Comment by wlerin** [comment]
It should be in `requirements.txt`

However, all the config file stuff this is used for is only half-finished, so I really need to work on that...

**Comment by skeith** [comment]
Will change this PR later or if you have plans to change it yourself, it's okay to close this.

**Comment by wlerin** [comment]
To follow up on this, I'm going to change how the config files work, and write some basic documentation for them. pyyaml will be added to requirements.txt when that happens.

**Pull request closed without merging**
